SELECT DISTINCT
  t1.PT_ID,
  t1.PT_ENC_ID,
  t1.ORD_DTTM,
  t1.START_DTTM,
  t1.END_DTTM,
  t1.PROC_DESCR,
  t1.CPT,
  t3.ORD_MODE_DESCR,
  t4.PT_DFCI_MRN
  FROM DART_ODS.ODS_EDW_ORD_PROC t1
    LEFT JOIN DART_ODS.ODS_EDW_ORD_PROC_03 t3 ON t1.ORD_PROC_ID = t3.ORD_ID
    LEFT JOIN DART_ODS.MV_COBA_PT_ENC t4 ON t1.PT_ENC_ID = t4.ENC_ID_CSN
WHERE t4.PT_BWH_MRN = '33480906'
;

SELECT DISTINCT
  t1.ORD_ID,
  t1.PT_ID,
  t1.PT_ENC_ID,
  t1.MED_DESCR
  FROM DART_ODS.ODS_EDW_ORD_MED t1
LEFT JOIN DART_ODS.MV_COBA_PT_ENC t2 ON t1.PT_ENC_ID = t2.ENC_ID_CSN
WHERE t1.PT_ENC_ID = 3187614350
      AND EXTRACT(YEAR FROM t1.ORD_DTTM) = 2018
AND EXTRACT(MONTH FROM t1.ORD_DTTM) = 1
AND EXTRACT(DAY FROM t1.ORD_DTTM) = 29
;


