SELECT DISTINCT
  t1.PT_ID,
  t1.PT_ENC_ID,
  t1.ORD_DTTM,
  t1.START_DTTM,
  t1.END_DTTM,
  t1.PROC_DESCR,
  t1.CPT,
  t3.ORD_MODE_DESCR
  FROM DART_ODS.ODS_EDW_ORD_PROC t1
    LEFT JOIN DART_ODS.ODS_EDW_ORD_PROC_03 t3 ON t1.ORD_PROC_ID = t3.ORD_ID
WHERE t1.PT_ENC_ID = 3109555229