--Figure out the 81 discrepancy
SELECT COUNT(*) AS CNT FROM (
  SELECT
    V_EDW_ENC_PT_ENC.APPT_DTTM                  ApptLDttm,
    V_EDW_ENC_PT_ENC.DEPT_DESCR                 DeptLDescr,
    V_EDW_PT_REGISTRY_ADDL.CUSTOM_COLM_02_DESCR CustomLColmL02LDescr,
    V_EDW_ENC_PT_ENC.APPT_STATE_DESCR           ApptLStateLDescr,
    V_EDW_ENC_PT_ENC.ENC_TYP_DESCR              EncLTypLDescr,
    V_EDW_REF_VISIT_TYP_RECORD.VISIT_TYP_DESCR  VisitLTypLDescr,
    V_EDW_ENC_PT_ENC.PT_ENC_ID                  PtLEncLId,
    V_EDW_ENC_PT_ENC.PRIM_LEVEL_OF_SVC_PROC_CD  PrimLLevelLOfLSvcLProcLCd,
    V_EDW_ENC_PT_ENC.ENC_CLOSED_DTTM            EncLClosedLDttm,
    V_EDW_ENC_PT_ENC.ENC_CLOSED_IND             EncLClosedLInd
  FROM DART_ODS.ODS_EDW_REF_VISIT_TYP_RECORD V_EDW_REF_VISIT_TYP_RECORD
    LEFT JOIN (
        DART_ODS.ODS_EDW_PT_REGISTRY_ADDL V_EDW_PT_REGISTRY_ADDL
        LEFT JOIN DART_ODS.ODS_EDW_ENC_PT_ENC V_EDW_ENC_PT_ENC
          ON (V_EDW_PT_REGISTRY_ADDL.PT_ID = V_EDW_ENC_PT_ENC.PT_ID)
      )
      ON V_EDW_REF_VISIT_TYP_RECORD.VISIT_TYP_ID = V_EDW_ENC_PT_ENC.VISIT_TYP_ID
  WHERE V_EDW_ENC_PT_ENC.DEPT_DESCR IN ('DF PALLIATIVE CARE', 'DF PSYCH ONC')
        AND EXTRACT(YEAR FROM V_EDW_ENC_PT_ENC.APPT_DTTM) = 2017
        AND V_EDW_ENC_PT_ENC.PT_ENC_ID NOT IN (
    SELECT
      V_EDW_ENC_PT_ENC.PT_ENC_ID
    FROM DART_ODS.ODS_EDW_REF_VISIT_TYP_RECORD V_EDW_REF_VISIT_TYP_RECORD
      LEFT JOIN (
          DART_ODS.ODS_EDW_PT_REGISTRY_ADDL V_EDW_PT_REGISTRY_ADDL
          LEFT JOIN (
            DART_ODS.ODS_EDW_REF_PROV REFER_PROV
            LEFT JOIN DART_ODS.ODS_EDW_ENC_PT_ENC V_EDW_ENC_PT_ENC
              ON REFER_PROV.EPIC_PROV_ID = V_EDW_ENC_PT_ENC.REFER_PROV_ID
          )
            ON (V_EDW_PT_REGISTRY_ADDL.PT_ID = V_EDW_ENC_PT_ENC.PT_ID)
        )
        ON V_EDW_REF_VISIT_TYP_RECORD.VISIT_TYP_ID = V_EDW_ENC_PT_ENC.VISIT_TYP_ID
    WHERE V_EDW_ENC_PT_ENC.DEPT_DESCR IN ('DF PALLIATIVE CARE', 'DF PSYCH ONC')
          AND EXTRACT(YEAR FROM V_EDW_ENC_PT_ENC.APPT_DTTM) = 2017
  )
);

--Count primary table records for comparison
SELECT COUNT(*) AS CNT
FROM
  dart_ods.ods_edw_enc_pt_enc t3
WHERE EXTRACT(YEAR FROM t3.APPT_DTTM) = 2017
      AND t3.DEPT_DESCR IN ('DF PALLIATIVE CARE', 'DF PSYCH ONC');

--Count MS SQL records for comparison
SELECT COUNT(DISTINCT PtLEncLId) AS CNT FROM (
  SELECT
    REFER_PROV.PROV_NM                          ProvLNm,
    V_EDW_ENC_PT_ENC.APPT_DTTM                  ApptLDttm,
    V_EDW_ENC_PT_ENC.DEPT_DESCR                 DeptLDescr,
    V_EDW_PT_REGISTRY_ADDL.CUSTOM_COLM_02_DESCR CustomLColmL02LDescr,
    V_EDW_ENC_PT_ENC.APPT_STATE_DESCR           ApptLStateLDescr,
    V_EDW_ENC_PT_ENC.ENC_TYP_DESCR              EncLTypLDescr,
    V_EDW_REF_VISIT_TYP_RECORD.VISIT_TYP_DESCR  VisitLTypLDescr,
    V_EDW_ENC_PT_ENC.PT_ENC_ID                  PtLEncLId,
    V_EDW_ENC_PT_ENC.PRIM_LEVEL_OF_SVC_PROC_CD  PrimLLevelLOfLSvcLProcLCd,
    V_EDW_ENC_PT_ENC.ENC_CLOSED_DTTM            EncLClosedLDttm,
    V_EDW_ENC_PT_ENC.ENC_CLOSED_IND             EncLClosedLInd
  FROM DART_ODS.ODS_EDW_REF_VISIT_TYP_RECORD V_EDW_REF_VISIT_TYP_RECORD
    LEFT JOIN (
        DART_ODS.ODS_EDW_PT_REGISTRY_ADDL V_EDW_PT_REGISTRY_ADDL
          LEFT JOIN (
            DART_ODS.ODS_EDW_REF_PROV REFER_PROV
              LEFT JOIN DART_ODS.ODS_EDW_ENC_PT_ENC V_EDW_ENC_PT_ENC
              ON REFER_PROV.EPIC_PROV_ID = V_EDW_ENC_PT_ENC.REFER_PROV_ID
          )
          ON (V_EDW_PT_REGISTRY_ADDL.PT_ID = V_EDW_ENC_PT_ENC.PT_ID)
      )
      ON V_EDW_REF_VISIT_TYP_RECORD.VISIT_TYP_ID = V_EDW_ENC_PT_ENC.VISIT_TYP_ID
  WHERE V_EDW_ENC_PT_ENC.DEPT_DESCR IN ('DF PALLIATIVE CARE', 'DF PSYCH ONC')
        AND EXTRACT(YEAR FROM V_EDW_ENC_PT_ENC.APPT_DTTM) = 2017)
