SELECT
  t1.PROV_ID,
  t1.PROV_NM,
  t1.PROV_TYPE_DESCR,
  t1.PROV_STATUS_CD,
  t1.PROV_PRIM_DEPT_DESCR,
  t1.PROV_DX_TYPE_DV
FROM DART_ODS.MV_COBA_PROV t1
WHERE t1.PROV_NM LIKE '%FERNANDEZ%JORGE%'
   OR t1.PROV_NM LIKE '%BERK%DEBORAH%'
   OR t1.PROV_NM LIKE '%GROSE%AMY%'
   OR t1.PROV_NM LIKE '%AUGUST%JUDITH%'
   OR t1.PROV_NM LIKE '%FOOTER%DANA%'
   OR t1.PROV_NM LIKE '%SIDA%CHARLOTTE%'
   OR t1.PROV_NM LIKE '%CHOW%CANDICE%'