SELECT
  t1.TRANSACT_ID,
  t1.CPT,
  t1.HOSP_ACCT_ID,
  t1.PT_ENC_ID,
  t1.ORIG_REVRSE_TRANSACT_ID,
  t1.ORIG_LATE_CHG_COR_TRANSACT_ID,
  t1.ORIG_LATE_CHG_CRED_TRANSACT_ID,
  t1.POST_DTTM,
  t1.SVC_DTTM,
  t1.TRANSACT_CNT,
  t1.TRANSACT_AMT,
  t1.HOSP_ACCT_CLS_DESCR,
  t1.BILL_PROV_ID
FROM
  dart_ods.ods_edw_fin_hosp_transact t1
WHERE
  t1.BILL_PROV_ID = '1014799'
  AND EXTRACT(YEAR FROM t1.SVC_DTTM) = 2017
  AND EXTRACT(MONTH FROM t1.SVC_DTTM) = 12
  AND t1.CPT IN ('99205')
;