--F_MTHLY_PROV_SERVICE_RVU Testing
SELECT
  t1.PROC_DIM_SEQ,
  t1.BEG_MTH_DIM_SEQ,
  t1.TOT_SERVICE_QTY,
  t1.PROC_DIM_SEQ,
  t2.EPIC_PROV_ID,
  t2.PROV_NM,
  t3.CPT_CD
FROM dartedm.F_MTHLY_PROV_SERVICE_RVU t1
  LEFT JOIN dartedm.D_PROV t2 ON t1.PROV_DIM_SEQ = t2.PROV_DIM_SEQ
  LEFT JOIN dartedm.D_PROC t3 ON t1.PROC_DIM_SEQ = t3.PROC_DIM_SEQ
WHERE t2.EPIC_PROV_ID = '1014799'
      AND t3.CPT_CD = '99205'
ORDER BY t1.BEG_MTH_DIM_SEQ;

--F_PROV_EFFORT_RVU
SELECT
  t1.*,
  t4.DFCI_MRN
FROM DARTEDM.F_PROV_EFFORT_RVU t1
  LEFT JOIN dartedm.D_PROV t2 ON t1.PROV_DIM_SEQ = t2.PROV_DIM_SEQ
  LEFT JOIN dartedm.D_PROC t3 ON t1.PROC_DIM_SEQ = t3.PROC_DIM_SEQ
  LEFT JOIN dartedm.D_PATIENT t4 ON t1.PATIENT_DIM_SEQ = t4.PATIENT_DIM_SEQ
WHERE t2.EPIC_PROV_ID = '1014799'
      AND t3.CPT_CD = '99205'
      AND SERVICE_DT_DIM_SEQ BETWEEN 20171201 AND 20171231;

--F_PATIENT_SERVICE
SELECT
  t1.*,
  t4.CPT_CD
FROM dartedm.f_patient_service t1
  LEFT JOIN dartedm.D_PROV t2 ON t1.PROV_DIM_SEQ = t2.PROV_DIM_SEQ
  LEFT JOIN dartedm.D_PROC t3 ON t1.PROC_DIM_SEQ = t3.PROC_DIM_SEQ
  LEFT JOIN dartedm.D_PROC t4 ON t1.PROC_DIM_SEQ = t4.PROC_DIM_SEQ
WHERE t2.EPIC_PROV_ID = '1014799'
      --AND t3.CPT_CD = '99205'
      AND SERVICE_DT_DIM_SEQ BETWEEN 20171201 AND 20171231;



