SELECT
  t1.PATIENT_DIM_SEQ,
  t1.INS_RANK,
  t1.PAYOR_NM,
  t1.BENEFIT_PLAN_NM,
  t2.FIRST_NM,
  t2.LAST_NM
  FROM DARTEDM.V_PT_CURRENT_INSURANCE t1
LEFT JOIN DARTEDM.D_PATIENT t2 ON t1.PATIENT_DIM_SEQ = t2.PATIENT_DIM_SEQ
WHERE t2.EPIC_PATIENT_ID = 'Z11274185'